version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: kst_postgres
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: kst_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 